[package]
name = "stm32f41x"
version = "0.1.0"
authors = ["Jacob Creedon <jcreedon@gmail.com>"]

[dependencies]
bare-metal = "0.2.0"
cortex-m = "0.5.0"
vcell = "0.1.0"

[dependencies.cortex-m-rt]
optional = true
version = "0.5.0"

[features]
rt = ["cortex-m-rt/device"]
